config/routes.rb
Rails.application.routes.draw do



  root :to => 'pages#home'

  get '/users/edit' => 'users#edit'
  resources :users, :only => [:new, :create, :index, :update, :show]

  get '/signup' => 'users#new'

  get '/login' => 'session#new'
  post 'login' => 'session#create'

  delete '/logout' => 'session#destroy'



  get 'dance' => 'pages#dance'
  get 'dj' => 'pages#dj'
  get 'drums' => 'pages#drums'
  get 'cubes' => 'pages#cubes'
  get 'piano' => 'pages#piano'
  get 'snapshot' => 'pages#snapshot'


end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :text
#  email           :text
#  image_url       :string
#  password_digest :string
#  admin           :boolean          default(FALSE)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base

  has_secure_password

  validates :email, :presence => true, :uniqueness => true

  def default_username
      "monster" + rand(10 ** 4).to_s + id.to_s
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :fetch_user
  
  private
  def fetch_user
   @current_user = User.find_by :id => session[:user_id] if session[:user_id].present?
   session[:user_id] = nil unless @current_user.present?
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def drums
    if @current_user.nil?
      flash[:error] = 'You must be logged in to see Drum Monster'
      redirect_to login_path
    end
  end

  def piano

  end

  def dj
    if @current_user.nil?
      flash[:error] = 'You must be logged in to see DJ Monster'
      redirect_to login_path
    end
  end

  def dance

  end

  def snapshot

  end

  def cubes

  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  def new
  end

  def create
    user = User.find_by :email => params[:email]
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      # log in
      redirect_to user_path(user)
    # elsif
    #   !user
    #   redirect_to signup_path
    else
      flash[:error]='Incorrect email or password'
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params

    # @user.name ||= @user.default_username



    if @user.save
      if @user.name.blank?
        @user.name = @user.default_username
        @user.save
      end
      session[:user_id] = @user.id
      redirect_to @user
    else
      puts @user.errors
      render 'new'
    end
  end

  def show
    @user = @current_user
  end

  def edit
    @user = @current_user

  end

  def update
    @user = @current_user
    if @user.update user_params
      # if user_params[:image_url]
      #   req = Cloudinary::Uploader.upload user_params[:image_url]
      #   @user.image_url = req["url"]
      # end

      @user.save
      redirect_to user_path(@user)
    else
      # redirect_to user_path(@user)
      render 'edit'
    end
  end


  private
  def user_params
    params.require(:user).permit(:name, :country, :city, :bio, :email, :password, :password_confirmation, :image_url)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicalMonsters</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= csrf_meta_tags %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/gsap/1.18.2/TweenMax.min.js' %>

  </head>
  <body>
    <header class="header__container">
      <div class="header__logo">

      </div>
      <h1 class="header__title">

        <svg id="Layer_1" class="header__monster" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 318 362.2">
          <title>monster-dance</title>
          <g id="body">
            <path d="M230.7,303a55.3,55.3,0,0,1,36.7,9.6c15.5,10.7,12.2,34.5-5.6,40.5s-46.3,11.4-75.2,3.5a27.6,27.6,0,0,1-20.2-24.2l-1.8-20.3" style="fill: #534741;stroke: #000;stroke-miterlimit: 10;stroke-width: 3px"/>
            <path d="M81.5,303a55.3,55.3,0,0,0-36.7,9.6c-15.5,10.7-12.2,34.5,5.6,40.5s46.3,11.4,75.2,3.5a27.6,27.6,0,0,0,20.2-24.2l1.8-20.3" style="fill: #534741;stroke: #000;stroke-miterlimit: 10;stroke-width: 3px"/>
            <path d="M289.3,200.8c0,40.5-11.9,77.5-31.6,106.1-65.7,11.5-139,16.1-202,.1C36,278.4,24.1,241.3,24.1,200.8c0-90.4,59.4-163.7,132.6-163.7S289.3,110.4,289.3,200.8Z" style="fill: #39b54a;stroke: #000;stroke-miterlimit: 10;stroke-width: 3px"/>
            <g>
              <ellipse cx="122.8" cy="107.8" rx="22.1" ry="26.4" style="fill: #fff;stroke: #000;stroke-miterlimit: 10;stroke-width: 3px"/>
              <ellipse cx="126.1" cy="115.8" rx="9.5" ry="11.2" style="stroke: #000;stroke-miterlimit: 10;stroke-width: 3px"/>
            </g>
            <g>
              <ellipse cx="179.1" cy="107.8" rx="22.1" ry="26.4" style="fill: #fff;stroke: #000;stroke-miterlimit: 10;stroke-width: 3px"/>
              <ellipse cx="176" cy="113.6" rx="9.5" ry="11.2" style="stroke: #000;stroke-miterlimit: 10;stroke-width: 3px"/>
            </g>
            <g>
              <path d="M99.9,152.3l3,25.7h22.8l-21.3-27.5A2.5,2.5,0,0,0,99.9,152.3Z" style="fill: #fff;stroke: #000;stroke-miterlimit: 10;stroke-width: 3px"/>
              <path d="M199.4,178l3-25.7a2.5,2.5,0,0,0-4.5-1.9L176.6,178h22.8Z" style="fill: #fff;stroke: #000;stroke-miterlimit: 10;stroke-width: 3px"/>
              <line x1="125.5" y1="178.3" x2="176.5" y2="178.3" style="fill: #fff;stroke: #000;stroke-miterlimit: 10;stroke-width: 3px"/>
            </g>
            <line x1="181" y1="31.8" x2="181" y2="31.8" style="fill: #c1272d;stroke: #000;stroke-miterlimit: 10;stroke-width: 3px"/>
          </g>
          <g id="left-arm">
            <path d="M70.4,190s19,40.2,0,60.3S-4,256.4,1.9,219.8c3-18.2,38.6-38.1,38.6-38.1" style="fill: #39b54a;stroke: #000;stroke-miterlimit: 10;stroke-width: 3px"/>
          </g>
          <g id="hat">
            <path d="M232.2,45.9a104.2,104.2,0,0,1-19.9,5.5" style="fill: #c1272d;stroke: #000;stroke-miterlimit: 10;stroke-width: 3px"/>
            <path d="M148.2,36.9A65.7,65.7,0,0,1,138,28.1" style="fill: #c1272d;stroke: #000;stroke-miterlimit: 10;stroke-width: 3px"/>
            <path d="M212,51.4a84.6,84.6,0,0,1-64-14.5h0C149,35.6,202.3-50.9,212,51.4Z" style="fill: #c1272d;stroke: #000;stroke-miterlimit: 10;stroke-width: 3px"/>
          </g>
          <g id="arm-right">
            <path d="M247.6,190s-19,40.2,0,60.3,74.5,6.2,68.5-30.4c-3-18.2-38.6-38.1-38.6-38.1" style="fill: #39b54a;stroke: #000;stroke-miterlimit: 10;stroke-width: 3px"/>
          </g>
        </svg>

        <%= link_to 'Musical Monsters', root_path %></h1>

    </header>

    <nav class="nav__container">
      <ul class="nav__list">
        <li class="nav__list-item"><%= link_to 'HOME', root_path %></li>
        <li class="nav__list-item"><%= link_to 'DANCE', dance_path %></li>
        <li class="nav__list-item"><%= link_to 'DRUMS', drums_path %></li>
        <li class="nav__list-item"><%= link_to 'PIANO', piano_path %></li>
        <li class="nav__list-item"><%= link_to 'DJ', dj_path %></li>
        <li class="nav__list-item"><%= link_to 'CUBES', cubes_path %></li>
        <li class="nav__list-item"><%= link_to 'SNAPSHOT', snapshot_path %></li>
      </ul>
    </nav>

    <main class="main__container">
      <%= yield %>
    </main>

  <footer class="footer__container">
    <ul class="footer__list">
      <!--  CONDITIONAL LINKS -->
      <!--  if user is logged in -->
      <% if @current_user.present? %>
      <li class="footer__list-item"><%= link_to 'PROFILE', user_path(@current_user) %></li>
      <li class="footer__list-item"><%= link_to "LOGOUT", logout_path, :method => :delete %></li>

      <!--  User is NOT logged in -->
      <% else %>
      <li class="footer__list-item"><%= link_to 'SIGN UP', signup_path %></li>
      <li class="footer__list-item"><%= link_to 'LOGIN', login_path %></li>

      <% end %>
      <!--  END CONDITIONAL LINKS -->

      <li class="footer__list-item footer__nav-toggle">MENU</li>



    </ul>

  </footer>

  </body>
</html>

app/views/pages/blob.html.erb
<h2 class="main__title">Blobs</h2>


<div class="btn-container">
  <button id="play" class="btn">Play</button>
  <button id="stop" class="btn">Stop</button>
  <button id="snapshot" class="btn">Snapshot</button>
</div>


  <div class="snapshot__tooltip">
    <div class="snapshot__tooltip--line1"></div>
    <div class="snapshot__tooltip--line2">Input signal: <span class="snapshot__tooltip--line2-details"></span></div>
  </div>

  <div class="snapshot-svg__container">
    <svg id="snapshot-svg" class="snapshot-svg" width="700" height="400"></svg>
  </div>

<%= javascript_include_tag 'd3.v3.min.js' %>
<%= javascript_include_tag 'blob.js' %>

app/views/pages/cubes.html.erb
<%= javascript_include_tag 'three.min.js' %>
<%= javascript_include_tag 'orbitControls.js' %>
<%= javascript_include_tag 'axisHelper.js' %>
<%= javascript_include_tag 'datGui.js' %>


<h2 class="main__title">CUBES</h2>

<div class="btn-container">
  <div id="play" class="btn">Play</div>
  <div id="pause" class="btn">Pause</div>
</div>

<div class="sounds__container"></div>

<%= javascript_include_tag 'cubes.js' %>

app/views/pages/dance-2d.html.erb
<h2 class="main__title">2D Dance</h2>


<div class="canvas__container">
  <canvas id="canvas__equalizer" class="canvas__equalizer"></canvas>
  <canvas id="canvas__volume" class="canvas__volume"></canvas>
</div>

<div class="btn-container">
  <div id="play" class="btn">Play</div>
  <div id="pause" class="btn">Pause</div>
</div>


<div class="monster__container">
  <%= image_tag 'm-body.png', :class => 'monster__body' %>
  <%= image_tag 'm-hat.png', :class => 'monster__hat' %>
  <%= image_tag 'm-left.png', :class => 'monster__arm-left' %>
  <%= image_tag 'm-right.png', :class => 'monster__arm-right' %>
</div>

<%= javascript_include_tag 'main.js' %>

app/views/pages/dance.html.erb
<h2 class="main__title">DANCE</h2>

<div class="canvas__container">
  <canvas id="canvas__equalizer" class="canvas__equalizer"></canvas>
  <canvas id="canvas__volume" class="canvas__volume"></canvas>
</div>

<div class="dance__container">
  <div class="dance-search__container">
    <input id="input-dance-search" class="dance-search__input" type="text" placeholder="Type in a song name" value="Filter">
    <label for=""></label>


  <div class="dance-btn__container">
    <button id="soundcloud-search" class="btn btn-soundcloud">SoundCloud</button>
    <button id="spotify-search" class="btn btn-spotify">Spotify</button>
  </div>

  <div class="dance-btn__container">
    <div id="play" class="btn">Play</div>
    <div id="pause" class="btn">Pause</div>
  </div>

    <div class="dance-results__container">
      <div class="dance-tracks__container">
        <h3>Tracks</h3>
        <ul class="dance-tracks__list"></ul>
      </div>
    </div>
  </div>

<div class="monster__container">
  <%= image_tag 'm-body.png', :class => 'monster__body' %>
  <%= image_tag 'm-hat.png', :class => 'monster__hat' %>
  <%= image_tag 'm-left.png', :class => 'monster__arm-left' %>
  <%= image_tag 'm-right.png', :class => 'monster__arm-right' %>
</div>

</div>

<%= javascript_include_tag 'dance.js' %>

app/views/pages/dj.html.erb
<h2 class="main__title">Monster DJ</h2>


<div class="dj__container">
  <svg id="Layer_1" class="dj__svg" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 314.7 266.4">
    <title>monster-dj</title>
    <path d="M583.3,364.6a29.6,29.6,0,0,1,19.7,5.1,12.3,12.3,0,0,1-3,21.7c-10.2,3.5-24.8,6.1-40.3,1.9a14.8,14.8,0,0,1-10.8-12.9l-1-10.9" transform="translate(-359.8 -131.2)" style="fill: #534741;stroke: #000;stroke-miterlimit: 10;stroke-width: 1.6072937389407707px"/>
    <path d="M451.5,364.6a29.6,29.6,0,0,0-19.7,5.1,12.3,12.3,0,0,0,3,21.7c10.2,3.5,24.8,6.1,40.3,1.9a14.8,14.8,0,0,0,10.8-12.9l1-10.9" transform="translate(-359.8 -131.2)" style="fill: #534741;stroke: #000;stroke-miterlimit: 10;stroke-width: 1.6072937389407707px"/>
    <path d="M610.1,280.4c0,32-8.3,61.2-22.1,83.8-45.9,9.1-97.2,12.8-141.2.1-13.8-22.6-22.1-51.8-22.1-83.8,0-71.4,41.5-129.3,92.7-129.3S610.1,209,610.1,280.4Z" transform="translate(-359.8 -131.2)" style="fill: #93278f;stroke: #000;stroke-miterlimit: 10;stroke-width: 2.090688164802941px"/>
    <g>
      <ellipse cx="137.9" cy="71.6" rx="15.2" ry="18.3" style="fill: #fff;stroke: #000;stroke-miterlimit: 10;stroke-width: 2.0721799116531794px"/>
      <ellipse cx="140.1" cy="77.1" rx="6.6" ry="7.8" style="stroke: #000;stroke-miterlimit: 10;stroke-width: 2.0721799116531794px"/>
    </g>
    <g>
      <ellipse cx="176.8" cy="71.6" rx="15.2" ry="18.3" style="fill: #fff;stroke: #000;stroke-miterlimit: 10;stroke-width: 2.0721799116531794px"/>
      <ellipse cx="174.6" cy="75.5" rx="6.6" ry="7.8" style="stroke: #000;stroke-miterlimit: 10;stroke-width: 2.0721799116531794px"/>
    </g>
    <g id="mouth">
      <path d="M481.9,233.6l2.1,17.8h15.7l-14.7-19.1A1.7,1.7,0,0,0,481.9,233.6Z" transform="translate(-359.8 -131.2)" style="fill: #fff;stroke: #000;stroke-miterlimit: 10;stroke-width: 2.0721799116531794px"/>
      <path d="M550.6,251.4l2.1-17.8a1.7,1.7,0,0,0-3.1-1.2l-14.7,19.1h15.7Z" transform="translate(-359.8 -131.2)" style="fill: #fff;stroke: #000;stroke-miterlimit: 10;stroke-width: 2.0721799116531794px"/>
      <line x1="139.7" y1="120.2" x2="175" y2="120.2" style="fill: #fff;stroke: #000;stroke-miterlimit: 10;stroke-width: 2.0721799116531794px"/>
    </g>
    <line x1="170.3" y1="67.7" x2="170.3" y2="67.7" style="fill: #c1272d;stroke: #000;stroke-miterlimit: 10;stroke-width: 1.6072937389407707px"/>
    <g id="hat">
      <path d="M557,155.8a55.8,55.8,0,0,1-10.7,2.9" transform="translate(-359.8 -131.2)" style="fill: #c1272d;stroke: #000;stroke-miterlimit: 10;stroke-width: 1.6072937389407707px"/>
      <path d="M512,150.9a35.2,35.2,0,0,1-5.5-4.7" transform="translate(-359.8 -131.2)" style="fill: #c1272d;stroke: #000;stroke-miterlimit: 10;stroke-width: 1.6072937389407707px"/>
      <path d="M546.2,158.7a45.3,45.3,0,0,1-34.3-7.8h0C512.4,150.3,541,103.9,546.2,158.7Z" transform="translate(-359.8 -131.2)" style="fill: #c1272d;stroke: #000;stroke-miterlimit: 10;stroke-width: 1.6072937389407707px"/>
    </g>
    <polygon points="313.6 211.2 1.1 211.2 21.1 177.6 293.6 177.6 313.6 211.2" style="fill: #4d4d4d;stroke: #000;stroke-linecap: round;stroke-linejoin: round;stroke-width: 2.144px"/>
    <ellipse cx="227.7" cy="193.8" rx="59.9" ry="12.5" style="fill: #999;stroke: #000;stroke-miterlimit: 10;stroke-width: 2.1442179719500456px"/>
    <g id="right-arm">
      <path d="M567.7,286.5s-28.1,21.5-10,32.3,71,3.3,65.3-16.3c-2.8-9.7-26.9-20.4-26.9-20.4" transform="translate(-359.8 -131.2)" style="fill: #93278f;stroke: #000;stroke-miterlimit: 10;stroke-width: 2.1442179719500456px"/>
    </g>
    <ellipse cx="86.4" cy="193.8" rx="59.9" ry="12.5" style="fill: #999;stroke: #000;stroke-miterlimit: 10;stroke-width: 2.1442179719500456px"/>
    <g id="left-arm">
      <path d="M466.1,286.5s28.1,21.5,10,32.3-71,3.3-65.3-16.3c2.8-9.7,26.9-20.4,26.9-20.4" transform="translate(-359.8 -131.2)" style="fill: #93278f;stroke: #000;stroke-miterlimit: 10;stroke-width: 2.1442179719500456px"/>
    </g>
    <rect x="1.1" y="211.2" width="312.6" height="12.52" style="fill: #4d4d4d;stroke: #000;stroke-linejoin: round;stroke-width: 2.144px"/>
    <rect x="299.6" y="223.7" width="14.1" height="41.61" style="fill: #4d4d4d;stroke: #000;stroke-linejoin: round;stroke-width: 2.144px"/>
    <rect x="1.1" y="223.7" width="14.1" height="41.61" style="fill: #4d4d4d;stroke: #000;stroke-linejoin: round;stroke-width: 2.144px"/>
  </svg>
</div>


<div class="dj-controls__container">
  <div class="dj-controls__left">

    <input type="radio" name="loops-slow" id="r-loop-1" value="0" checked>
    <label class="label-dj" for="r-loop-1">1</label>

    <input type="radio" name="loops-slow" id="r-loop-2" value="1">
    <label class="label-dj" for="r-loop-2">2</label>

    <input type="radio" name="loops-slow" id="r-loop-3" value="2">
    <label class="label-dj" for="r-loop-3">3</label>

  </div>
  <div class="dj-controls__middle">
    <input class="dj-range" type="range" min="0" max="100" value="0">
  </div>
  <div class="dj-controls__right">
    <input type="radio" name="loops-fast" id="r-loop-4" value="3" checked>
    <label class="label-dj" for="r-loop-4">4</label>

    <input type="radio" name="loops-fast" id="r-loop-5" value="4">
    <label class="label-dj" for="r-loop-5">5</label>

    <input type="radio" name="loops-fast" id="r-loop-6" value="5">
    <label class="label-dj" for="r-loop-6">6</label>
  </div>
</div>

<div class="dj-controls__container">

    <div id="start-spinning" class="btn">Start Spinning!</div>
    <div id="stop-spinning" class="btn">Silence!</div>

</div>

<div class="dj__instructions">
  Tracks loading...
</div>

<%= javascript_include_tag 'dj.js' %>

app/views/pages/sounds-3d.html.erb
<%= javascript_include_tag 'three.min.js' %>
<%= javascript_include_tag 'orbitControls.js' %>
<%= javascript_include_tag 'axisHelper.js' %>
<%= javascript_include_tag 'datGui.js' %>


<h2 class="main__title">Sounds 3D</h2>

<div class="btn-container">
  <div id="play" class="btn">Play</div>
  <div id="pause" class="btn">Pause</div>
</div>

<div class="sounds__container"></div>

<%= javascript_include_tag 'sounds-3d.js' %>

app/views/session/new.html.erb
<h2 class="main__title">LOGIN</h2>
<div class="login-container">

  <!--  Display error from login fail (redirect from login `else`)-->
  <% if flash[:error].present? %>
  <h3 class="forms__error-heading">
    <%= flash[:error] %>
  </h3>
  <% end %>

  <%= form_tag login_path, :class => 'form' do %>

  <fieldset>
    <%= label_tag :email, nil, :class => 'label' %>
    <%= text_field_tag :email, nil, :class => 'input' %>
  </fieldset>

  <fieldset>
    <%= label_tag :password, nil , :class => 'label' %>
    <%= password_field_tag :password, nil, :class => 'input' %>
  </fieldset>

  <div class="btn-container">
    <%= submit_tag "Login", :class => 'btn' %>
  </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<h2 class="main__title">EDIT PROFILE</h2>


<%= form_for @user, :html => {:class => 'form'} do |f| %>

<fieldset>
  <%= f.label :name, :class => 'label'  %>
  <%= f.text_field :name, :class => 'input'  %>
</fieldset>

<fieldset>
  <%= f.label :email, :class => 'label'  %>
  <%= f.email_field :email, :required => true, :class => 'input'  %>
</fieldset>

<% if !@current_user.present? %>
<fieldset>
  <%= f.label :password, :class => 'label' %>
  <%= f.password_field :password, :required => true, :class => 'input' %>
</fieldset>

<fieldset>
  <%= f.label :password_confirmation, "Confirm password", :class => 'label' %>
  <%= f.password_field :password_confirmation, :required => true, :class => 'input' %>
</fieldset>
<% end %>

<fieldset>
  <%= f.label :image, :class => 'label'  %>
  <%= f.file_field :image_url, :class => 'input' %>
</fieldset>

<div class="btn-container">
  <%= f.submit "Save Profile", :class => 'btn' %>
</div>

<% end %>

app/views/users/new.html.erb
<h2 class="main__title">SIGNUP</h2>


<%= form_for @user, :html => {:class => 'form'} do |f| %>

<% if @user.errors.any? %>
    <% @user.errors.full_messages.each do |msg| %>
      <h3 class="forms__error-heading"><%= msg %></h3>
    <% end %>
<% end %>

<% if flash[:error].present? %>
<h3 class="forms__error-heading">
  <%= flash[:error] %>
</h3>
<% end %>

<fieldset>
  <%= f.label :email, :class => 'label'  %>
  <%= f.email_field :email, :required => true, :class => 'input'  %>
</fieldset>

<fieldset>
  <%= f.label :password, :class => 'label' %>
  <%= f.password_field :password, :required => true, :class => 'input' %>
</fieldset>

<fieldset>
  <%= f.label :password_confirmation, "Confirm password", :class => 'label' %>
  <%= f.password_field :password_confirmation, :required => true, :class => 'input' %>
</fieldset>

<div class="btn-container">
  <%= f.submit "Signup", :class => 'btn' %>
</div>

<% end %>

app/views/users/show.html.erb
<h2 class="main__title">PROFILE</h2>

<div class="profile__container">
  <p><strong>NAME:</strong>
    <%= @user.name %></p>
  <p><strong>EMAIL:</strong>
    <%= @user.email %></p>

  <div class="btn-container">
    <%= link_to "Edit Profile", users_edit_path, :class => 'btn' %>
  </div>
</div>